---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: unit tests
    pull: if-not-exists
    image: ecr.tooling.dvla.gov.uk/base-images/qe-ruby:2.7.0-1
    commands:
      - bundle --jobs 5 --quiet
      - bundle exec rspec
    when:
      event:
        - push

  - name: build
    pull: if-not-exists
    image: ecr.tooling.dvla.gov.uk/base-images/qe-ruby:2.7.0-1
    commands:
      - bundle --jobs 5
      - gem build super-symbolize.gemspec
      - gem install nexus -v 1.4.0
      - gem nexus --url https://nexus.tooling.dvla.gov.uk/repository/gem-private/ super-symbolize*gem
    when:
      branch:
        - master
    depends_on:
      - unit tests