AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.4

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

Gemspec/RequireMFA:
  Enabled: false

Metrics/BlockLength:
  Max: 120
  Exclude:
    - spec/**/*.rb

Style/MixinUsage:
  Enabled: false

Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 20