AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.0

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

Gemspec/RequireMFA:
  Enabled: false

Metrics/BlockLength:
  Max: 120
  Exclude:
    - spec/**/*.rb

Style/MixinUsage:
  Enabled: false

Lint/BooleanSymbol:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Max: 25

Layout/LineLength:
  Max: 130